# Generated by Django 3.0.6 on 2020-05-20 09:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_subtitle', models.CharField(blank=True, default='', max_length=120)),
                ('post_body', models.TextField()),
                ('post_created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
