# Generated by Django 3.0.6 on 2020-05-19 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_subtitle',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
