# Generated by Django 3.0.6 on 2020-05-19 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
