# Generated by Django 3.0.6 on 2020-05-19 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20200519_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
